import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f4f6fb',
  },
  mainScroll: {
    flex: 1,
  },
  authBox: {
    flex: 1,
    padding: 24,
    justifyContent: 'center',
  },
  header: {
    marginTop: 8,
    marginBottom: 8,
    paddingTop: 18,
    paddingBottom: 18,
    paddingHorizontal: 24,
    borderRadius: 22,
    backgroundColor: '#1c2f8f',
  },
  mainTitle: {
    fontSize: 28,
    fontWeight: '700',
    color: '#0f172a',
  },
  mainTitleLight: {
    fontSize: 24,
    fontWeight: '700',
    color: '#fff',
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: 30,
  },
  subtitle: {
    fontSize: 16,
    marginTop: 10,
    color: '#334155',
  },
  lastUpdate: {
    marginTop: 8,
    color: '#cbd5e1',
    fontSize: 14,
  },
  content: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 12,
  },
  quoteBanner: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    paddingVertical: 8,
    paddingHorizontal: 18,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.07,
    shadowRadius: 6,
    elevation: 2,
  },
  quoteBannerTitle: {
    fontSize: 20,
    fontWeight: '700',
    textAlign: 'center',
    color: '#0f172a',
  },
  quoteBannerSubtitle: {
    marginTop: 0,
    fontSize: 12,
    textAlign: 'center',
    color: '#475569',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 16,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
  },
  cardMainRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: 8,
  },
  flagContainer: {
    width: 42,
    height: 42,
    marginRight: 10,
    justifyContent: 'center',
  },
  primaryFlag: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  secondaryFlag: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: '#ffffff',
    position: 'absolute',
    right: 0,
    bottom: 0,
  },
  cardTitle: {
    flex: 1,
  },
  cardName: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0f172a',
  },
  cardCode: {
    fontSize: 10,
    color: '#64748b',
    marginTop: 2,
  },
  cardValue: {
    fontSize: 22,
    fontWeight: '700',
    color: '#0f172a',
    textAlign: 'right',
  },
  buttonContainer: {
    marginTop: 12,
    marginHorizontal: 24,
  },
  footer: {
    marginTop: 'auto',
    paddingTop: 8,
    paddingBottom: 10,
    paddingHorizontal: 14,
    backgroundColor: '#f4f6fb',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
  },
  userRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  userText: {
    color: '#334155',
    fontSize: 11,
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  navItem: {
    color: '#94a3b8',
    fontSize: 11,
  },
  navItemActive: {
    color: '#0f172a',
    fontWeight: '700',
  },
  input: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    color: '#0f172a',
  },
  toggleRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 24,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cbd5e1',
    backgroundColor: '#fff',
    marginHorizontal: 4,
  },
  toggleActive: {
    backgroundColor: '#0f172a',
    borderColor: '#0f172a',
  },
  toggleText: {
    textAlign: 'center',
    color: '#334155',
    fontWeight: '700',
  },
  toggleTextActive: {
    color: '#fff',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#eef2ff',
  },
  errorText: {
    marginTop: 12,
    marginHorizontal: 24,
    color: '#b91c1c',
    fontSize: 13,
    textAlign: 'center',
  },
  refreshButtonWrapper: {
    marginTop: 8,
  },
  refreshButton: {
    backgroundColor: '#46b6b3',
    borderRadius: 26,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0f172a',
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  refreshButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
});

export default styles;
